# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpilimit',
            name='owner',
        ),
        migrations.AddField(
            model_name='kpi',
            name='better_when',
            field=models.CharField(default='upper', max_length=5),
        ),
        migrations.AddField(
            model_name='kpi',
            name='lower_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='upper_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='KpiLimit',
        ),
    ]
